version: '3.7'
services:
  api:
    image: 831119889470.dkr.ecr.eu-central-1.amazonaws.com/mangoweb/contember/api:$CONTEMBER_VERSION
    volumes:
      - ./api/config.yaml:/src/config.yaml:cached
      - ../../projects:/src/projects:cached
    environment:
      CONTEMBER_CONFIG_FILE: /src/config.yaml
      CONTEMBER_PROJECTS_DIRECTORY: /src/projects
      NODE_ENV: development
      CONTEMBER_PORT: 4000
      CONTEMBER_S3_SERVER: minio
    depends_on:
      - db

  admin:
    image: node:12
    volumes:
      - ../../:/src
    working_dir: /src
    expose:
      - 4000
    command: npm run start-admin

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: contember
      POSTGRES_USER: contember
      POSTGRES_DB: contember
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  adminer:
    image: michalhosna/adminer:4.7.0-517ba68
    depends_on:
      - db
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: db
      ADMINER_DB: contember
      ADMINER_USERNAME: contember
      ADMINER_PASSWORD: contember
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Contember
  s3:
     image: minio/minio
     command: server /data
     volumes:
       - s3-data:/data
     environment:
       MINIO_ACCESS_KEY: contember
       MINIO_SECRET_KEY: contember
volumes:
  pgsql-data: ~
  s3-data: ~
